'use client'
import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, ChevronDown, Download, ExternalLink, Mail, Menu, X } from 'lucide-react'
import { siGithub, siLinkedin, siDiscord, siJavascript, siTypescript, siPython, siReact, siNodedotjs, siPostgresql, siGit, siMongodb, siFigma } from 'simple-icons/icons'
import portfolioData, { socialLabels, visibleSocialLinks } from './data/portfolioData'

const d = portfolioData
function BrandIcon({ icon, size = 16 }) { return <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true"><path d={icon.path}/></svg> }
const iconMap = { email: Mail, github: (p) => <BrandIcon icon={siGithub} {...p}/>, linkedin: (p) => <BrandIcon icon={siLinkedin} {...p}/>, discord: (p) => <BrandIcon icon={siDiscord} {...p}/> }
const skillBrandIcons = { JavaScript: siJavascript, TypeScript: siTypescript, Python: siPython, React: siReact, 'Node.js': siNodedotjs, PostgreSQL: siPostgresql, Git: siGit, MongoDB: siMongodb, Figma: siFigma }

function Preloader() { const [show, setShow] = useState(true); useEffect(() => { const t = setTimeout(() => setShow(false), 900); return () => clearTimeout(t) }, []); return <AnimatePresence>{show && <motion.div className="preloader" initial={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="spinner center">{Array.from({ length: 12 }).map((_, i) => <div className="spinner-blade" key={i}/>)}</div></motion.div>}</AnimatePresence> }
function Button({ children, variant = 'primary', ...props }) { return <a className={`button ${variant}`} {...props}>{children}</a> }
function Socials({ compact = false }) { return <div className={`socials ${compact ? 'compact' : ''}`}>{visibleSocialLinks(d.socialLinks).map(([key, url]) => { const Icon = iconMap[key]; return <a key={key} href={url} target="_blank" rel="noreferrer" aria-label={socialLabels[key]}>{Icon ? <Icon size={16}/> : <span aria-hidden="true">{socialLabels[key].slice(0, 2).toUpperCase()}</span>}</a> })}</div> }
function Navbar({ onResume }) { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const items = [['about','About'],['skills','Skills'],['services','Services'],['projects','Projects'],['experience','Experience'],['contact','Contact']]; useEffect(() => { const on = () => setScrolled(window.scrollY > 20); window.addEventListener('scroll', on); return () => window.removeEventListener('scroll', on) }, []); useEffect(() => { const on = (e) => e.key === 'Escape' && setOpen(false); window.addEventListener('keydown', on); return () => window.removeEventListener('keydown', on) }, []); return <header className={`nav-wrap ${scrolled ? 'scrolled' : ''}`}><nav className="nav container"><a className="wordmark" href="#home">{d.personalInfo.initials}<span>.</span></a><div className={`nav-links ${open ? 'open' : ''}`}>{items.map(([id,label]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}{d.personalInfo.resumeUrl && <button className="nav-resume" onClick={() => { setOpen(false); onResume() }}>Resume</button>}</div><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X/> : <Menu/>}</button></nav></header> }
function Hero({ onResume }) { const [index, setIndex] = useState(0); useEffect(() => { const t = setInterval(() => setIndex((i) => (i + 1) % d.heroContent.titles.length), 2500); return () => clearInterval(t) }, []); return <section id="home" className="hero"><div className="container hero-grid"><div><p className="eyebrow">{d.heroContent.eyebrow}</p><h1>{d.personalInfo.name}</h1><div className="hero-title"><span>I&apos;m a </span><AnimatePresence mode="wait"><motion.strong key={d.heroContent.titles[index]} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}>{d.heroContent.titles[index]}</motion.strong></AnimatePresence></div><p className="hero-summary">{d.personalInfo.summary}</p><div className="button-row"><Button href="#projects">{d.heroContent.ctaLabel}<ArrowUpRight size={16}/></Button><Button href="#contact" variant="secondary">Contact me</Button>{d.personalInfo.resumeUrl && <button className="text-button" onClick={onResume}>View resume</button>}</div></div><div className="hero-aside"><span className="line"/><p>Based in<br/><strong>{d.personalInfo.location}</strong></p><Socials compact/><span className="scroll-cue">Scroll to explore <ChevronDown size={15}/></span></div></div></section> }
function About() { return <section id="about" className="about-section about-simple-section"><div className="container about-simple"><p className="eyebrow">01 / About</p><h2>About Me</h2><p className="about-intro">{d.aboutContent.introBefore} <strong>{d.personalInfo.name}</strong> {d.aboutContent.introAfter}</p>{d.aboutContent.paragraphs.map((p) => <p key={p}>{p}</p>)}<div className="interest-list">{d.aboutContent.interests.map((i) => <span key={i}>{i}</span>)}</div></div></section> }
function SkillIcon({ skill }) { const brand = skillBrandIcons[skill.name]; if (brand) return <BrandIcon icon={brand} size={26}/>; if (skill.icon === 'ui') return <span className="ui-icon" aria-hidden="true"><i/><b/></span>; return <span className="skill-mark" aria-hidden="true">{skill.mark}</span> }
function Skills() { return <section id="skills" className="dark-section skills-section"><div className="glow glow-one"/><div className="glow glow-two"/><div className="container"><div className="center-heading"><p className="eyebrow light">Technical Stack</p><h2>My Skillset</h2><p>Languages, frameworks, databases, and engineering concepts I use to turn ideas into reliable software.</p></div><div className="skill-grid">{d.technicalSkills.map((skill, i) => <motion.article className="skill-tile" key={skill.name} initial={{ opacity: 0, scale: .92 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: .2 }} transition={{ delay: i * .045, duration: .4 }}><div className="skill-icon"><SkillIcon skill={skill}/></div><strong>{skill.name}</strong><span>{skill.category}</span><div className="progress"><i style={{ width: `${skill.level}%` }}/></div></motion.article>)}</div></div></section> }
function Services() { return <section id="services" className="section soft-bg"><div className="container"><p className="eyebrow">03 / What I can build</p><div className="section-heading"><h2>Useful software,<br/><em>carefully made.</em></h2></div><div className="service-grid">{d.services.map((s) => <article className="service-card" key={s.title}><span className="service-number">{s.mark}</span><h3>{s.title}</h3><p>{s.description}</p><div className="tag-row">{s.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></div></section> }
function Projects() { return <section id="projects" className="section"><div className="container"><p className="eyebrow">04 / Selected projects</p><div className="section-heading projects-heading"><h2>Proof of<br/><em>practice.</em></h2><p>Projects are where ideas become constraints, tradeoffs, and working software.</p></div><div className="project-grid">{d.projects.map((p) => <article className={`project-card ${p.featured ? 'featured' : ''}`} key={p.title}><div className="project-art"><span>{p.mark}</span><small>{p.status}</small></div><div className="project-body"><div className="project-top"><h3>{p.title}</h3>{p.featured && <span className="badge">Featured</span>}</div><p>{p.description}</p><p className="problem"><strong>Problem:</strong> {p.problem}</p><div className="feature-list">{p.features.map((f) => <span key={f}>{f}</span>)}</div><div className="project-footer"><div className="tag-row">{p.tech.map((t) => <span key={t}>{t}</span>)}</div><div className="project-links">{p.github && <a href={p.github} target="_blank" rel="noreferrer" aria-label={`${p.title} GitHub`}><span aria-hidden="true">GH</span></a>}{p.liveDemo && <a href={p.liveDemo} target="_blank" rel="noreferrer" aria-label={`${p.title} live demo`}><ExternalLink size={17}/></a>}</div></div></div></article>)}</div></div></section> }
function Experience() { return <section id="experience" className="section soft-bg"><div className="container two-col"><div><p className="eyebrow">05 / Experience</p><h2>Learning by<br/><em>doing the work.</em></h2></div><div className="timeline">{d.internships.length === 0 ? <div className="empty-state"><span>01</span><h3>Building experience through practice.</h3><p>Currently building experience through academic, personal, and open-source projects.</p></div> : d.internships.map((x) => <article key={x.organization}><span>{x.duration}</span><h3>{x.position} · {x.organization}</h3><p>{x.responsibilities}</p></article>)}{d.leadership.map((x) => <article key={x.title}><span>{x.meta}</span><h3>{x.title}</h3><p>{x.detail}</p></article>)}</div></div></section> }
function BeyondCode() { return <section className="dark-section beyond section"><div className="container"><p className="eyebrow light">06 / {d.contentSection.eyebrow}</p><h2>{d.contentSection.heading}</h2><div className="beyond-grid">{d.contentSection.cards.map((c, i) => <motion.article key={c.label} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .35 }} transition={{ delay: i * .12 }}><span>0{i + 1}</span><h3>{c.label}</h3><p>{c.text}</p></motion.article>)}</div></div></section> }
function Contact() { const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false); const submit = (e) => { e.preventDefault(); setLoading(true); setTimeout(() => { setLoading(false); setStatus('Thanks — your message is ready to be connected.'); e.currentTarget.reset() }, 700) }; return <section id="contact" className="contact-section"><div className="contact-dot"/><div className="container"><p className="eyebrow">07 / Get in touch</p><h2>Let&apos;s build<br/><em>something.</em></h2><p className="contact-lead">{d.footerContent.tagline} I&apos;m open to thoughtful collaborations, internships, and ambitious problems.</p><form className="contact-form" onSubmit={submit}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label className="message-field">Message<textarea required name="message" rows="3" placeholder="Tell me a little about what you&apos;re building." /></label><div className="submit-row"><span>{status || 'I usually reply within a few days.'}</span><button className="button primary" disabled={loading}>{loading ? 'Sending…' : 'Send message'} <ArrowUpRight size={16}/></button></div></form><div className="links-grid">{[['github','GitHub',d.socialLinks.github],['linkedin','LinkedIn',d.socialLinks.linkedin],['discord','Discord',d.socialLinks.discord],['email','Email',`mailto:${d.personalInfo.email}`]].filter(([, , url]) => url).map(([key, label, url], i) => { const Icon = iconMap[key]; return <a className="contact-link" key={key} href={url} target={key === 'email' ? undefined : '_blank'} rel={key === 'email' ? undefined : 'noreferrer'}><small>0{i + 1}</small><span className="contact-icon">{Icon ? <Icon size={17}/> : <span aria-hidden="true">{label.slice(0, 2).toUpperCase()}</span>}</span><strong>{label}</strong><ArrowUpRight className="link-arrow" size={18}/></a> })}</div></div></section> }
function ResumeModal({ onClose }) { useEffect(() => { const on = (e) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', on); return () => window.removeEventListener('keydown', on) }, [onClose]); return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><motion.div className="resume-modal" role="dialog" aria-modal="true" aria-labelledby="resume-title" initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }}><div className="modal-head"><h2 id="resume-title">Resume</h2><button onClick={onClose} aria-label="Close resume"><X/></button></div><iframe title="Resume PDF" src={d.personalInfo.resumeUrl}/><div className="modal-actions"><Button href={d.personalInfo.resumeUrl} download>Download <Download size={16}/></Button><Button href={d.personalInfo.resumeUrl} target="_blank" rel="noreferrer" variant="secondary">Open in new tab <ExternalLink size={16}/></Button></div></motion.div></motion.div> }
function Footer() { return <footer className="footer"><div className="container footer-row"><span className="footer-brand">{d.personalInfo.name}<b>.</b></span><span>© {new Date().getFullYear()} · {d.footerContent.tagline}</span><a href="#home" aria-label="Back to top">Back to top ↑</a></div></footer> }
export default function App() { const [resume, setResume] = useState(false); return <><Preloader/><Navbar onResume={() => setResume(true)}/><main><Hero onResume={() => setResume(true)}/><About/><Skills/><Services/><Projects/><Experience/><BeyondCode/><Contact/></main><Footer/>{resume && <ResumeModal onClose={() => setResume(false)}/>}</> }
